<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.2.269">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Ángel García, Arnau Piferrer, Guillem Serra">

<title>Entrega 1</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1.6em;
  vertical-align: middle;
}
</style>


<script src="Entrega1_files/libs/clipboard/clipboard.min.js"></script>
<script src="Entrega1_files/libs/quarto-html/quarto.js"></script>
<script src="Entrega1_files/libs/quarto-html/popper.min.js"></script>
<script src="Entrega1_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="Entrega1_files/libs/quarto-html/anchor.min.js"></script>
<link href="Entrega1_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="Entrega1_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="Entrega1_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="Entrega1_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="Entrega1_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">


</head>

<body class="fullcontent">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Entrega 1</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Ángel García, Arnau Piferrer, Guillem Serra </p>
          </div>
  </div>
    
  
    
  </div>
  

</header>

<p>Este es el <a href="https://github.com/GSMir/Entrega1.git">repositorio</a> de GitHub dónde se puede encontrar todo el trabajo realizado en este proyecto.</p>
<div class="cell">
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'palmerpenguins' was built under R version 4.2.3</code></pre>
</div>
</div>
<div class="cell">

</div>
<p>Hay 344 observaciones de pingüinos, y 8 variables diferentes.</p>
<section id="vamos-a-estudiar-cada-una-de-las-variables" class="level2">
<h2 class="anchored" data-anchor-id="vamos-a-estudiar-cada-una-de-las-variables">Vamos a estudiar cada una de las variables:</h2>
<p>Primero de todo, veamos qué variables tenemos:</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>[1] "bill_depth_mm"     "bill_length_mm"    "body_mass_g"      
[4] "flipper_length_mm" "island"            "sex"              
[7] "species"           "year"             </code></pre>
</div>
</div>
<p>Ahora hacemos un estudio de cada una de las variables.</p>
<section id="species" class="level3">
<h3 class="anchored" data-anchor-id="species">Species</h3>
<div class="cell">

</div>
<p>Es una variable del tipo ´r clasevariable´. Hace referéncia a la especie del pingüino.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>   Adelie Chinstrap    Gentoo 
      152        68       124 </code></pre>
</div>
</div>
<p>Podemos observar que hay 3 especies diferentes, “Adelie”, “Chinstrap” y “Gentoo”.</p>
</section>
<section id="island" class="level3">
<h3 class="anchored" data-anchor-id="island">Island</h3>
<div class="cell">

</div>
<p>Es una variable del tipo ´r clasevariable´. Hace referéncia a la isla en la que habitan los pingüinos</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>   Biscoe     Dream Torgersen 
      168       124        52 </code></pre>
</div>
</div>
<p>Podemos observar que hay 3 islas diferentes, “Biscoe”, “Dream” y “Torgersen”.</p>
</section>
<section id="bill_length_mm" class="level3">
<h3 class="anchored" data-anchor-id="bill_length_mm">Bill_length_mm</h3>
<div class="cell">

</div>
<p>Es una variable del tipo ´r clasevariable´.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>   Min. 1st Qu.  Median    Mean 3rd Qu.    Max.    NA's 
  32.10   39.23   44.45   43.92   48.50   59.60       2 </code></pre>
</div>
</div>
<p>Hace referencia a la longitud del pico de los pingüinos, en mm. Va en un rango de 32.1mm a 59.6mm. Con una media de 43.92mm, con 44.45mm de mediana, y una desviación típica de 5.46.</p>
</section>
<section id="bill_depth_mm" class="level3">
<h3 class="anchored" data-anchor-id="bill_depth_mm">Bill_depth_mm</h3>
<div class="cell">

</div>
<p>Es una variable del tipo ´r clasevariable´.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>   Min. 1st Qu.  Median    Mean 3rd Qu.    Max.    NA's 
  13.10   15.60   17.30   17.15   18.70   21.50       2 </code></pre>
</div>
</div>
<p>Hace referencia a la amplitud del pico de los pingüinos, en mm. Va en un rango de 13.1mm a 21.5mm. Con una media de 17.15mm, con 17.30mm de mediana y una desviación típica de 1.97.</p>
</section>
<section id="flipper_length_mm" class="level3">
<h3 class="anchored" data-anchor-id="flipper_length_mm">Flipper_length_mm</h3>
<div class="cell">

</div>
<p>Es una variable del tipo ´r clasevariable´.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>   Min. 1st Qu.  Median    Mean 3rd Qu.    Max.    NA's 
  172.0   190.0   197.0   200.9   213.0   231.0       2 </code></pre>
</div>
</div>
<p>Hace referencia a la longitud de las aletas de los pingüinos, en mm. Va en un rango de 172.0mm a 231.0mm. Con una media de 200.9mm, con 197mm de mediana y una desviación típica de 14.06.</p>
</section>
<section id="body_mass_g" class="level3">
<h3 class="anchored" data-anchor-id="body_mass_g">Body_mass_g</h3>
<div class="cell">

</div>
<p>Es una variable del tipo ´r clasevariable´.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>   Min. 1st Qu.  Median    Mean 3rd Qu.    Max.    NA's 
   2700    3550    4050    4202    4750    6300       2 </code></pre>
</div>
</div>
<p>Hace referencia al peso de los pingüinos, en g. Va en un rango de 2700g a 6300g. Con una media de 4202g, con 4050g de mediana y una desviación típica de 801.95.</p>
</section>
<section id="sex" class="level3">
<h3 class="anchored" data-anchor-id="sex">Sex</h3>
<div class="cell">

</div>
<p>Es una variable del tipo ´r clasevariable´. Hace referencia al sexo cromosómico de los pingüinos.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>female   male   NA's 
   165    168     11 </code></pre>
</div>
</div>
<p>Podemos observar que hay 165 observaciones de hembras, y 168 observaciones de machos.</p>
</section>
<section id="year" class="level3">
<h3 class="anchored" data-anchor-id="year">Year</h3>
<div class="cell">

</div>
<p>Es una variable del tipo ´r clasevariable´. Hace referencia al año en que nacieron los pingüinos. Observemos que esta variable tendría más sentido tratarla como factor, y para ejecutar el summary lo trataremos como tal.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>2007 2008 2009 
 110  114  120 </code></pre>
</div>
</div>
<p>Podemos observar que los pingüinos, del estudio fueron observados a lo largo de 3 años diferentes; 2007, 2008, 2009.</p>
</section>
</section>
<section id="veamos-ahora-algunos-gráficos" class="level2">
<h2 class="anchored" data-anchor-id="veamos-ahora-algunos-gráficos">Veamos ahora algunos gráficos:</h2>
<section id="gráficos-generales" class="level3">
<h3 class="anchored" data-anchor-id="gráficos-generales">Gráficos generales</h3>
<div class="cell">
<div class="cell-output-display">
<p><img src="Entrega1_files/figure-html/unnamed-chunk-19-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
<section id="especies-vs-islas" class="level3">
<h3 class="anchored" data-anchor-id="especies-vs-islas">Especies vs islas</h3>
<div class="cell">
<div class="cell-output-display">
<p><img src="Entrega1_files/figure-html/unnamed-chunk-20-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
<section id="especies-vs-sexo" class="level3">
<h3 class="anchored" data-anchor-id="especies-vs-sexo">Especies vs sexo</h3>
<div class="cell">
<div class="cell-output-display">
<p><img src="Entrega1_files/figure-html/unnamed-chunk-21-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
<section id="especies-vs-año-de-avistamiento" class="level3">
<h3 class="anchored" data-anchor-id="especies-vs-año-de-avistamiento">Especies vs año de avistamiento</h3>
<div class="cell">
<div class="cell-output-display">
<p><img src="Entrega1_files/figure-html/unnamed-chunk-22-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
<section id="diagrama-de-caja-y-bigotes" class="level3">
<h3 class="anchored" data-anchor-id="diagrama-de-caja-y-bigotes">Diagrama de caja y bigotes:</h3>
<p>Mediana de la longitud de los picos por especie.</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="Entrega1_files/figure-html/unnamed-chunk-23-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>A priori vemos que la mediana de la longitud de los picos de Adelie es más pequeña que el resto de las otras dos. Para confirmar que la longitud media del pico de Adelie también será inferior a la de las otras dos especies (por tener medianas y dispersiones tan diferentes), sería necesario realizar un contraste de hipótesis para confirmarlo.</p>
<p>Mediana de la amplitud de los picos por especies:</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="Entrega1_files/figure-html/unnamed-chunk-24-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Parece que la amplitud de los picos de Gentoo es más pequeña que las otras dos. Del mismo modo que antes, parece que, un rasgo distintivo de los Gentoo frente a las otras dos especies sería la amplitud del pico, que por lo general será más pequeña. Sería preciso hacer un contraste para determinarlo con mayor grado de confianza.</p>
<p>Mediana de la longitud de las alas por especies:</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="Entrega1_files/figure-html/unnamed-chunk-25-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>A partir del diagrama se puede deducir que, de encontrarnos un ejemplar de cada especie, lo más probable es que el Gentoo sea aquel con las alas más grandes.</p>
<p>Mediana de la masa corporal de los pingüinos por especies:</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="Entrega1_files/figure-html/unnamed-chunk-26-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Otro rasgo característico de los Gentoo sería la masa, que se puede ver en el gráfico que, por lo general, será mayor que la de Adelie o Chinstrap. Al igual que antes, de las 3 especies, esperaríamos que los Gentoo sean los más pesados.</p>
<p>En definitiva, algunas conclusiones obtenidas sobre el conjunto de datos serían:</p>
<p>1) De las 3 especies solamente Adelie habita en todas las islas (Adelie). La especie Chinstrap es endémica de la isla Dream y la especie Gentoo únicamente habita en Biscoe.</p>
<p>2) Si nos encontramos varios individuos una forma de distinguir los ejemplares de Adelie frente a las demás especies es a partir de la longitud del pico, que será más corto.</p>
<p>3) Algunos rasgos característicos propios de los Gentoo (que nos permitiría diferenciarlo de las otras especies) son la masa elevada, el mayor tamaño de las alas y un pico más estrecho que el resto.</p>
<p>4) Aquellos pingüinos que no encajen ni en el perfil de Adelie ni en el de Gentoo encajará, seguramente, con los individuos de la especie Chinstrap.</p>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>